# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Percent Euclidean climatch score
#'
#' Number of climatch scores >=6 in recipient region divided by number of rows of data (i.e., grid cells)
#'
#' @param recipient List of data.frames of the recipient regions
#' @param source List of data.frames of the source regions
#' @param globvar Vector of the global variance of each variable
#'
#' @return Percent climatch scores within recipient >=6
#' @importFrom Rcpp evalCpp
#' @export
#' @examples
#' i <- as.data.frame(matrix(runif(n=180, min=1, max=20), nrow=60)) # Fake source climate data.
#' j <- as.data.frame(matrix(runif(n=300, min=10, max=40), nrow=100)) # Fake recipient data.
#' variance <- c(600, 800, 450) # Fake global variance
#'
#' climatch_perc(recipient = j, source = i, globvar = variance)
climatch_perc <- function(recipient, source, globvar) {
    .Call(`_Euclimatch_climatch_perc`, recipient, source, globvar)
}

#' Euclidean climatch scores
#'
#' Vector of the climatch scores within the recipient region
#'
#' @param recipient List of data.frames of the recipient regions
#' @param source List of data.frames of the source regions
#' @param globvar Vector of the global variance of each variable
#'
#' @return Vector of climatch scores corresponding to each grid cell within recipient
#' @export
#' @examples
#' i <- as.data.frame(matrix(runif(n=180, min=1, max=20), nrow=60)) # Fake source climate data.
#' j <- as.data.frame(matrix(runif(n=300, min=10, max=40), nrow=100)) # Fake recipient data.
#' variance <- c(600, 800, 450) # Fake global variance
#'
#' climatch_vec(recipient = j, source = i, globvar = variance)
climatch_vec <- function(recipient, source, globvar) {
    .Call(`_Euclimatch_climatch_vec`, recipient, source, globvar)
}

